### ISSUE TITLE
Preview embedded in VSCode

### ISSUE THREAD

**Issue by jamesblasco** [jamesblasco/flutter_preview#5]
The final goal would be to integrate Flutter preview inside VSCode. This code editor allows embedded views through a webview, so the preview would be running on Flutter web

For having a pleasant experience these are needed:

- [ ] Allow flutter web debug apps to run inside an iframe [#61788] https://github.com/flutter/flutter/issues/61788)
- [ ] Hot reload for web [#53041](https://github.com/flutter/flutter/issues/53041)
- [ ] Allow getting an Image from a widget in web (for screenshots) [#42767](https://github.com/flutter/flutter/issues/42767)

**Comment by jamesblasco** [comment]
Some progress here, I managed to embed it inside vscode. Still some work to do to support hot restart

<img width="1003" alt="Captura de pantalla 2020-07-23 a las 17 29 56" src="https://user-images.githubusercontent.com/19904063/88307981-d41a0c80-cd0c-11ea-9eb1-6640180b7400.png">

**Comment by maks** [comment]
I can't seem to get this to work - is it available in the currently published vscode plugin or do I need to build the plugin myself?

**Comment by jamesblasco** [comment]
It doesn't work now as it needs some changes in the Flutter repo. I have already submitted a PR

**Comment by maks** [comment]
I'm assuming it's [this one](https://github.com/flutter/flutter/pull/62115), will keep an eye for it to be merged and then keen to come back and try this out again! 👍

**Comment by easazade** [comment]
this is a great feature for this package. I really look forward to use this feature
